# Problem Set 2 - Data preparation

_Data Preparation Course at UCU, 2019_

### NB

__1) Which programming languages to use?__

You can use Python, R or both of them (but with one limitation: one dataset - one language).

__2) What libraries/packages to use?__

You are free to choose any appropriate data processing libraries (good choice would be __pandas__, __numpy__ or
__pyspark__ for Python and __dplyr__ or __tidyr__ for R).

__3) How to summarize my homework?__

The best way is to create an individual Jupyter/R notebook with code and explanations for each dataset.
In case you are not familiar with these tools, you can create a Python/R scripts and write explanations
as comments. However, we strongly recommend you to use Jupyter/R notebooks, as those are #1 tools in
applied data analysis nowadays.

### Task 3

### Data normalization (Pima Indians Diabetes Database)

Load the appropriate libraries.

In [11]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
from sklearn import preprocessing
% matplotlib inline

UsageError: Line magic function `%` not found.

__3.1.__ Download the dataset from Kaggle [__(dataset)__](https://www.kaggle.com/uciml/pima-indians-diabetes-database#diabetes.csv).

In [12]:
df = pd.read_csv('diabetes.csv')
df.head(20)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

__3.2.__ Investigate the attributes and propose which of them need to be normalized? Explain your choice.

As for me, it looks like the insulin and glucose columns are  bit out of scale. And they may play less important role in the prediction.

In [13]:
df.max()

Pregnancies                  17.00
Glucose                     199.00
BloodPressure               122.00
SkinThickness                99.00
Insulin                     846.00
BMI                          67.10
DiabetesPedigreeFunction      2.42
Age                          81.00
Outcome                       1.00
dtype: float64

Decimal Scaling Method For Normalization:

In [14]:
df['Insulin'] = df['Insulin']/10
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0.0,33.6,0.627,50,1
1,1,85,66,29,0.0,26.6,0.351,31,0
2,8,183,64,0,0.0,23.3,0.672,32,1
3,1,89,66,23,9.4,28.1,0.167,21,0
4,0,137,40,35,16.8,43.1,2.288,33,1

__3.3.__ Perform normalization using the most appropriate method. Why did you choose it? How can you check
that it works better than others?

For this dataset I think that it would be best to use the min max normalization. Most of the data is in range 0 - 100 so i think it makes sense to use minMax normalization.

In [15]:
data = df.values 
minMaxScaler = preprocessing.MinMaxScaler()
scaledData = minMaxScaler.fit_transform(data)
df = pd.DataFrame(scaledData)
df.columns = ['Pregnancies','Glucose','BloodPressure',
              'SkinThickness','Insulin','BMI',
              'DiabetesPedigreeFunction','Age','Outcome']

In [16]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333,1.0
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667,0.0
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333,1.0
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000,0.0
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000,1.0

__3.4.__ Why do we need to normalize numerical attributes?

It helps get more iformation from the data, for example when we have a coulumn that has values from 5000 to 5100, the diference between the min value and the maximum values is not so great, so this column will affect less the outcome then other columns while in the same time it can play a vital role in the outcome. So the data normalization helps you avoid this data ignorance so to say.

__3.5.__ What is standartization and how it differs from normalization?

The main purpose of the normalization is to bring the data into a range of 0 - 1. The standartization purpose is to transform the data into a way that it has a mean of 0 and a standard deviation of 1.